#%RAML 1.0 Library
usage: |
  This library defines set of scalar types which are expected to be used in annotation
  type declarations. It is expected that RAML processing tools knows and respect them when perform library expansion.
types:
  RAMLLocalExpression:
    type: string
    description: |
      This type allows to describe an expression on an instance of the type. Expression language is javascript
    example: this.x+this.y
  RAMLResponseExpression:
    type: string
    description: |
      This type allows to describe a reference to the element of response. It supports chaining of property accesses.
  RAMLRequestExpression:
    type: string
    description: |
      This type allows to describe a reference to the element of request. It supports chaining of property accesses.
  RAMLReferenceExpression:
    type: string
    description: |
      This type allows to describe a reference to the property of RAML type. For example
      `Person.name` is a reference to the property name of the type person,
      It is also allowed to chain property accesses like  in following example `Repository.owner.login`
      type name may be prefixed with library namespace.
    examples:
      Simple: Person.name
      Chaining: Repository.owner.login
      Qualified: github.Repository.owner.login
  RAMLTypeName:
    description: name of the RAML type, if the type comes from library name should be prefixed with library namespace.
    type: string
    examples:
      SimpleName: Person
      QualifiedName: teams.Person
