#%RAML 1.0 Library
annotationTypes:
    immutable: nil | boolean
    readonly: nil | boolean
    primary: nil| boolean #
    parent: nil | boolean #
    child: nil | boolean
    key: boolean #
    propOrder:
      type: string[]
